### ISSUE TITLE
How use on authetication

### ISSUE THREAD

**Issue by NandoSantana** [wmfrancia/Encryptor#1]
hi, great sample, how to use the decryptor on password coming out? to decrypt save the $hash or $salt in my database?

**Comment by wmfrancia** [comment]
You have to save both the Hash and salt of the original password. To decrypt a Password, or rather check if a password that is entered matches the associated DB one. You need to get the salt for the specified user trying to login and then use that salt in the following:

//The mypassword string should be changed to be the input password from the user trying to login. and the salt is the salt for that user taken from the DB previously.

$hash_dec = new Decryptor("mypassword",$salt);

//this tells you if the password was correct or not.
$hash_compare = $hash_dec->result;
